version: "3.5"
services:
  web:
    build: .
    command: >
      bash -c "python manage.py collectstatic -c --noinput &&
      gunicorn portfolio_project.wsgi --bind 0.0.0.0:8000"
    container_name: web
    tty: true
    restart: unless-stopped
    networks:
      - portfolio-network
    volumes:
      - /static/:/code/staticfiles/
    environment:
      - DJANGO_SECRET_KEY

  portfolio-nginx:
    build: ./nginx
    container_name: nginx
    ports:
      - 8001
    restart: unless-stopped
    networks:
      - proxy-network
      - portfolio-network
    volumes:
      - ./nginx/conf:/etc/nginx/conf.d
      - /var/log/nginx/:/var/log/nginx/
      - /static/:/static/
      - /ssl/:/ssl/
    depends_on:
      - web

networks:
  proxy-network:
    name: proxy-network
  portfolio-network:
    name: portfolio-network