version: "3"
services:
  web:
    build: .
    command: gunicorn portfolio_project.wsgi --bind 0.0.0.0:8000
    container_name: web
    tty: true
    expose:
      - 8000
    volumes:
      - staticfiles:/code/staticfiles/

  nginx:
    image: nginx:1.13
    container_name: nginx
    ports:
      - 80:80
    volumes:
      - ./nginx/conf:/etc/nginx/conf.d
      - /var/log/nginx/:/var/log/nginx/
      - staticfiles:/static/
    depends_on:
      - web

volumes:
  staticfiles: