version: "3"
services:
  web:
    build: .
    command: >
      bash -c "gunicorn portfolio_project.wsgi --bind 0.0.0.0:8000 &&
               python manage.py collectstatic -c --noinput"
    container_name: web
    tty: true
    expose:
      - 8000
    volumes:
      - /static/:/code/staticfiles/
    environment:
      - DJANGO_SECRET_KEY

  nginx:
    build: ./nginx
    container_name: nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/conf:/etc/nginx/conf.d
      - /var/log/nginx/:/var/log/nginx/
      - /static/:/static/
      - /ssl/:/ssl/
    depends_on:
      - web